### ISSUE TITLE
resizable old school

### ISSUE THREAD

**Issue by irtusb** [kennehisftw/runescape-loader#6]
can you add support for resizable mode in old school client?

just remove line 208 in [GameSelection.java](https://github.com/kennehisftw/runescape-loader/tree/master/src/io/github/kennehisftw/swing/GameSelection.java) (setResizable(false))

**Comment by Rakeyjakey** [comment]
Not sure if Kenneh is keeping an eye on this any more so I'll let him know.

**Comment by TheWyn** [comment]
Done.
